### ISSUE TITLE
Asignación de colores incorrecta

### ISSUE THREAD

**Issue by jesusgm** [jorgeatgu/apaga-luz#11]
![imagen](https://user-images.githubusercontent.com/3921853/140417762-64e4bc9c-ca42-44b5-94eb-3d4a2d3cf321.png)
El precio para las 15:00 está en naranja y es menor que el precio para las 02:00 que está en verde

**Comment by jorgeatgu** [comment]
Gracias por el aviso, el color estaba bien. 

El problema es que la API cuando son precios como 0.200 €/kWh no añade los ceros y devuelve el precio como 0.2 €/kWh, al final los tengo que añadir yo. Fijate en el precio de las 18:00, también le falta un 0. Eso si ahora había cambiado unas cosas y estaba cogiendo los datos antes de añadir los decimales, ya esta corregido.
