### ISSUE TITLE
Documentación,

### ISSUE THREAD

**Issue by Deses** [jorgeatgu/apaga-luz#2]
Hola, buenos días,

Podrías añadir información al readme, con información básica del proyecto, licencia y cómo ejecutar el programa?

Veo que la web https://api.esios.ree.es/archives/70/download_json devuelve datos tal cual. ¿hace falta pedir una clave API?

**Comment by jorgeatgu** [comment]
Actualizado el readme, cualquier duda me dices ;)

**Comment by Deses** [comment]
Gracias! La información que das es muy útil. 

A lo mejor hago algún proyectillo con una raspberry pi con esto. :)
