### ISSUE TITLE
Request: datos ordenados cronológicamente, no por precio.

### ISSUE THREAD

**Issue by estebanbouza** [jorgeatgu/apaga-luz#8]
Con la visualización ordenada por precio, a veces se hace difícil entender cuándo hay un tramo de 3-4 horas baratas.

Se podría hacer un botón "toggle" que permitiese ordenar por precios / ordenar por horas.

**Comment by jorgeatgu** [comment]
Es algo que me pedía mucha gente y que quería hacer. Ahora ya se puede ordenar por precio o por hora, por defecto se ordena por precio ;)
